name: identity_firebase_link
description: Authenticate using Email Link by Firebase for Identity package
version: 0.1.0
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase-link

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.1.0
  identity: ^0.1.0
  identity_firebase: ^0.1.0
  firebase_auth: ^0.15.3
  crypto: ^2.1.3
  shared_preferences: ^0.5.6
  firebase_dynamic_links: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter